name: Deploy Application on Heroku

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  Notify:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_NOTIFY_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFY_TOKEN }}
          message: |
            ✨ New Deployment! ✨

            📜 ${{ github.event.commits[0].message }}

            👤 ${{ github.actor }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  Deploy:
    #needs: [ Notify ]
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote --app $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        run: git push heroku master
  Verify:
    needs: [Deploy]
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      - uses: actions/checkout@v2
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://lucas-finance.herokuapp.com/api/v1/health
          max-attempts: 3
          retry-delay: 5s
      - name: Get Workflow Duration using curl
        run: |
          curl -u ${{ secrets.GH_USERNAME }}:${{ secrets.GH_ACCESS_TOKEN }} -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/LucaTaddeo/finance2.0/actions/runs/${{github.run_id}} | tee >(jq '.updated_at') >(jq '.created_at') >/dev/null
      - name: Notify Success on Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_NOTIFY_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFY_TOKEN }}
          message: |
            ✅ finance2.0 successfully deployed!