name: Deploy Application on Heroku

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  Notify:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_NOTIFY_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFY_TOKEN }}
          message: |
            ✨ New Deployment! ✨

            📜 ${{ github.event.commits[0].message }}

            👤 ${{ github.actor }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  Deploy:
    #needs: [ Notify ]
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      - uses: actions/checkout@v2
      - name: Deploy on heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "lucas-finance"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://lucas-finance.herokuapp.com/api/v1/health"
  Verify:
    needs: [Deploy]
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[deploy]')"
    steps:
      - uses: actions/checkout@v2
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://lucas-finance.herokuapp.com/api/v1/health
          max-attempts: 3
          retry-delay: 5s
      - name: Notify Success on Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_NOTIFY_TOKEN }}
          message: |
            ✅ finance2.0 successfully deployed!